# $schema: https://json.schemastore.org/github-workflow.json

name: "_ Build _"

on:
  workflow_call:

jobs:
  build:
    name: Build web-vault
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run pnpm build
        env:
          VW_DOMAIN: ${{ secrets.VW_DOMAIN }}
          FARO_API_KEY: ${{ secrets.FARO_API_KEY }}
          FARO_APP_ID: ${{ vars.FARO_APP_ID }}
          FARO_ENDPOINT: ${{ vars.FARO_ENDPOINT }}
          FARO_STACK_ID: ${{ vars.FARO_STACK_ID }}
          VITE_FARO_DSN: ${{ vars.VITE_FARO_DSN }}
          VITE_CLARITY_ID: ${{ vars.VITE_CLARITY_ID }}
        run: pnpm --filter @bitwarden/web-vault run build:oss:selfhost:prod

      - name: Set short git commit SHA
        id: commit-id
        run: echo "val=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Upload frontend dist
        uses: actions/upload-artifact@v7
        with:
          name: build-${{ steps.commit-id.outputs.val }}
          path: apps/web/build/
