# $schema: https://json.schemastore.org/github-workflow.json

name: "_ Deploy _"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  deploy:
    name: Deploy web-vault
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"

      - name: Set short git commit SHA
        id: commit-id
        run: echo "val=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Download builds
        uses: actions/download-artifact@v8
        with:
          name: build-${{ steps.commit-id.outputs.val }}
          path: apps/web/build/

      - name: Trim sourcemaps
        run: find apps/web/build/ -type f -name "*.map" -delete

      - name: Deploy to CDN
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: pnpm dlx wrangler deploy

      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.4

      - name: Deploy to server
        uses: wangyucode/sftp-upload-action@v3
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USER }}
          privateKey: ${{ secrets.SFTP_KEY }}
          localDir: ./apps/web/build/
          remoteDir: /web-vault
          exclude: 'assets/*, res/*, _*'
          forceUpload: true
          removeExtraFilesOnServer: true
